version: '3'
services:
  web:
    build: .
    ports:
      - 80:5000
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: adelphi
    ports:
      - 5433:5432
    